#!/bin/bash

# Load .env.local
export $(grep -v '^#' .env.local | xargs)

# Execute Cloud Build
gcloud builds submit --config cloudbuild.yaml \
  --project heidless-apps-0 \
  --substitutions=\
_NEXT_PUBLIC_FIREBASE_API_KEY="$NEXT_PUBLIC_FIREBASE_API_KEY",\
_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN="$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN",\
_NEXT_PUBLIC_FIREBASE_PROJECT_ID="$NEXT_PUBLIC_FIREBASE_PROJECT_ID",\
_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET="$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET",\
_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID="$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID",\
_NEXT_PUBLIC_FIREBASE_APP_ID="$NEXT_PUBLIC_FIREBASE_APP_ID",\
_NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID="$NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID",\
_NEXT_PUBLIC_FIREBASE_DATABASE_ID="$NEXT_PUBLIC_FIREBASE_DATABASE_ID",\
_NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY="${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY:-none}",\
_NEXT_PUBLIC_STRIPE_PRICE_STANDARD="$NEXT_PUBLIC_STRIPE_PRICE_STANDARD",\
_NEXT_PUBLIC_STRIPE_PRICE_PRO="$NEXT_PUBLIC_STRIPE_PRICE_PRO",\
_NEXT_PUBLIC_APP_URL="https://plantune-heidless-apps-0.a.run.app",\
_GEMINI_API_KEY="$GEMINI_API_KEY",\
_STRIPE_SECRET_KEY="${STRIPE_SECRET_KEY:-none}",\
_STRIPE_WEBHOOK_SECRET="${STRIPE_WEBHOOK_SECRET:-none}"
